- name: Update apt
  ansible.builtin.apt:
    update_cache: true

- name: Install Python
  ansible.builtin.apt:
    name: python3
    state: present

- name: Install pip
  ansible.builtin.apt:
    name: python3-pip
    state: present