- name: Install pip
  ansible.builtin.include_tasks:
    file: install_pip.yml

- name: Install Docker
  ansible.builtin.include_tasks:
    file: install_docker.yml

- name: Install Docker Compose
  ansible.builtin.include_tasks:
    file: install_compose.yml